### ISSUE TITLE
IO Exception [Android Studio]

### ISSUE THREAD

**Issue by Fossor** [flurry/upload-clients#11]
Hi there!
Got this IO Exeption when building release version.

```
15:24:33.940 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':android_wip:assembleRelease'.
15:24:34.210 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: default
15:24:34.211 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
15:24:34.211 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
15:24:34.211 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 9][route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
15:24:34.211 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Opening connection {s}->https://crash-metadata.flurry.com:443
15:24:34.357 [DEBUG] [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connecting to crash-metadata.flurry.com/74.6.34.62:443
15:24:34.358 [DEBUG] [org.apache.http.conn.ssl.SSLConnectionSocketFactory] Connecting socket to crash-metadata.flurry.com/74.6.34.62:443 with timeout 5000
15:24:39.358 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-9: Shutdown connection
15:24:39.358 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection discarded
15:24:39.358 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 9][route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]

15:24:39.358 [ERROR] [org.gradle.api.Project] IO Exception during request: GET https://crash-metadata.flurry.com/pulse/v1/project?fields[project]=apiKey&filter[project.apiKey]=HEREISMYREALKEY HTTP/1.1
```

**Comment by clayreimann** [comment]
@Fossor Thanks for the report. We're working on internal upgrades and missed this during the migration. We're addressing the problem and I'll let you know as soon as we have it cleared up.

**Comment by clayreimann** [comment]
@Fossor I believe that we have resolved this issue, would you try again and let us know if this is resolved?

**Comment by Fossor** [comment]
Thanks for reply. Got another Error.
```
18:28:35.544 [INFO] [org.gradle.api.Project] ProGuard uploaded to Flurry
18:28:35.544 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: default
18:28:35.544 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
18:28:35.544 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 3 of 20]
18:28:35.545 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 2][route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 0; route allocated: 1 of 2; total allocated: 3 of 20]
18:28:35.545 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-2: set socket timeout to 5000
18:28:35.545 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET /pulse/v1/project/822152/uploads/32944?fields[upload]=uploadStatus,failureReason HTTP/1.1
18:28:35.545 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
18:28:35.863 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection can be kept alive indefinitely
18:28:35.863 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection [id: 2][route: {s}->https://crash-metadata.flurry.com:443] can be kept alive indefinitely
18:28:35.863 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 2][route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 3 of 20]
18:28:40.863 [DEBUG] [org.gradle.api.Project] Upload still not processed after 5s
18:28:40.863 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: default
18:28:40.863 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
18:28:40.863 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 3 of 20]
18:28:40.864 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 2][route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 0; route allocated: 1 of 2; total allocated: 3 of 20]
18:28:40.864 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-2: set socket timeout to 5000
18:28:40.864 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET /pulse/v1/project/822152/uploads/32944?fields[upload]=uploadStatus,failureReason HTTP/1.1
18:28:40.864 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
18:28:41.173 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection can be kept alive indefinitely
18:28:41.173 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection [id: 2][route: {s}->https://crash-metadata.flurry.com:443] can be kept alive indefinitely
18:28:41.174 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 2][route: {s}->https://crash-metadata.flurry.com:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 3 of 20]

18:28:41.174 [ERROR] [org.gradle.api.Project] Upload not processed after 0s

18:28:41.174 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':android_wip:assembleRelease'
18:28:41.174 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :android_wip:assembleRelease FAILED
18:28:41.175 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 84: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
18:28:41.175 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :android_wip:assembleRelease (Thread[Daemon worker Thread 2,5,main]) completed. Took 14.812 secs.
18:28:41.175 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 2,5,main]] finished, busy: 21.705 secs, idle: 0.01 secs
18:28:41.176 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 84: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent

18:28:41.176 [ERROR] [org.gradle.BuildExceptionReporter] 
18:28:41.177 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
18:28:41.177 [ERROR] [org.gradle.BuildExceptionReporter] 
18:28:41.177 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
18:28:41.177 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':android_wip:assembleRelease'.
18:28:41.177 [ERROR] [org.gradle.BuildExceptionReporter] > Upload not processed after 0s
18:28:41.177 [ERROR] [org.gradle.BuildExceptionReporter] 
18:28:41.177 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
18:28:41.177 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 

18:28:41.177 [LIFECYCLE] [org.gradle.BuildResultLogger] 
18:28:41.178 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
```

**Comment by clayreimann** [comment]
Closing this issue as stale. If you are still experiencing problems please open a new issue

**Comment by heronghua** [comment]
I got this problem too.

14:10:20.922 [DEBUG] [org.apache.http.conn.ssl.SSLConnectionSocketFactory] Starting handshake
14:10:21.003 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-1040: Shutdown connection
14:10:21.003 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection discarded
14:10:21.004 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 1040][route: {s}->https://maven.aliyun.com:443][total kept alive: 0; route allocated: 0 of 20; total allocated: 0 of 20]
14:10:21.004 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Metadata of https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'
14:10:21.004 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Metadata of https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom' completed
14:10:21.008 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder] Flushing resolved configuration data in Binary store in C:\Users\vend_wsd_am_038\AppData\Local\Temp\gradle971300634404229301.bin. Wrote root 2.
14:10:21.011 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve dependencies of :classpath'
14:10:21.011 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :classpath' completed
14:10:21.011 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Apply script build.gradle to root project 'Camera2Basic''
14:10:21.012 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply script build.gradle to root project 'Camera2Basic'' completed
14:10:21.012 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.538 secs
14:10:21.012 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Notify afterEvaluate listeners of :' started
14:10:21.012 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Notify afterEvaluate listeners of :'
14:10:21.013 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Notify afterEvaluate listeners of :' completed
14:10:21.013 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 13: released lock on :
14:10:21.013 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Configure project :'
14:10:21.013 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Configure project :' completed
14:10:21.013 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Configure build'
14:10:21.013 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Configure build' completed
14:10:21.021 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
14:10:21.022 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 13: released lock on root.1
14:10:21.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:10:21.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:10:21.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:10:21.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:10:21.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred configuring root project 'Camera2Basic'.
14:10:21.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve all artifacts for configuration ':classpath'.
14:10:21.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not resolve com.android.tools.build:gradle:3.5.0.
14:10:21.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]      Required by:
14:10:21.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          project :
14:10:21.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not resolve com.android.tools.build:gradle:3.5.0.
14:10:21.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not get resource 'https://maven.aliyun.com/repository/public/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.

Any other way to solve this problem?  It's so stupid to download configuration from network , a good idea should not be like this.

**Comment by clayreimann** [comment]
@heronghua Based on the logs you posted, I'm not sure your problem is related to this issue. This is the issue with your gradle build:

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.0.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.5.0.
         > Could not get resource 'https://maven.aliyun.com/repository/public/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
```

It looks like your build was unable to find the core android tools from google, which your build is trying to get from `https://maven.aliyun.com`.

As to downloading configuration from the network, all build tools do this.

**Comment by heronghua** [comment]
Some cert thing is wrong with this site https://dl.google.com/****/gradle-3.5.0.pom ,thats why I use maven.aliyun.com.  
As to downloading configuration from the network, all build tools do this.  >  I dont think so .  We use eclipse before  ,and it  will not download so many things every  time after luanch.

**Comment by clayreimann** [comment]
@heronghua both maven and gradle (either of which can be used by either Eclipse or Android Studio–aka IntelliJ) need to check remote repositories for your build's dependencies. 

In this case, the dependency that gradle can't seem to find is Google's core android tools ([maven link](https://mvnrepository.com/artifact/com.android.tools.build/gradle/3.5.0)) which doesn't appear to have anything to do with Flurry's plugin.

**Comment by heronghua** [comment]
Sorry to blame wrong person.
