### ISSUE TITLE
Timeout uploading DSym file

### ISSUE THREAD

**Issue by sweigardc** [flurry/upload-clients#12]
I've setup upload-clients per instructions, archive fails uploading the Dsym with the following message. No useful information for troubleshooting. Any suggestions?

12:45:11 [INFO] upload-symbols.py:95	archive: /var/folders/z9/tg_t8vt533n5w2x702_2hp3m0000gn/T/tmpkBEl4p.tgz (3385945 b)
12:45:11 [INFO] upload-symbols.py:97	creating upload
12:45:11 [DEBUG] upload-symbols.py:278	Created upload {u'data': {u'relationships': {u'project': {u'data': {u'type': u'project', u'id': u'864976'}}}, u'attributes': {u'uploadType': u'IOS', u'contentLength': 3385945, u'modifiedDate': 1490114711561, u'creationDate': 1490114711561, u'uploadStatus': u'CREATED', u'failureReason': None}, u'type': u'upload', u'id': u'46750'}}
12:45:11 [INFO] upload-symbols.py:100	uploading file
error uploading file. <urlopen error [Errno 60] Operation timed out> <class 'urllib2.URLError'>
Command /bin/sh failed with exit code 1

**Comment by clayreimann** [comment]
Hi @sweigardc, we're currently doing some internal maintenance which is affecting our ability to process uploads. This should be cleared up in an hour or two, sorry for the inconvenience.

If you're still seeing this in, say, 4 hours please let us know but in all likelihood this should be working again well before then.
