### ISSUE TITLE
Bad Token

### ISSUE THREAD

**Issue by jackal47** [flurry/upload-clients#4]
Hi,

The script returns error:
```
[INFO] upload-symbols.py:84	fetching project
error looking up project. (GET https://crash-metadata.flurry.com/pulse/v1/project?filter[project.apiKey]=<project_key>&fields[project]=apiKey => 401) UNAUTHORIZED (Bad Token)
```

Tried to use the APIs from script manually and got the same: 401
Regenerated the API Access Token few times -- no luck.
Is the base url correct? Or should Pulse be enabled in my account?

I know this looks more like a Flurry API issue, or an issue with my account or keys, hence I also tried few calls from official documentation (http://api.flurry.com/...) to make sure my keys are ok. These APIs worked fine

Thanks!

**Comment by clayreimann** [comment]
Hi @jackal47 you'll need a [programmatic token](https://developer.yahoo.com/flurry/docs/api/code/apptoken/) this is not the same as the credentials you used to access `api.flurry.com/*`.

**Comment by jackal47** [comment]
Worked like a charm! Thanks a lot!
