### ISSUE TITLE
Exception "The value for property 'resValues' cannot be changed any further"

### ISSUE THREAD

**Issue by beprogressive** [flurry/upload-clients#47]
I get Exception while Gradle sync: `java.lang.IllegalStateException: The value for property 'resValues' cannot be changed any further`
Progect level build.gradle:
```
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
	
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
        classpath 'com.google.gms:google-services:4.3.10'

        def nav_version = "2.3.0"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
		
	classpath "gradle.plugin.com.flurry:symbol-upload:4.0.0"
    }
}
```
App level build.gradle:
```
apply plugin: "com.flurry.android.symbols"

flurryCrash {
    configPath "flurry.config"
}
```
flurry.config in progect root
```
[flurry]
token=<My very long token>
api-key=<My API key>
```
![image](https://user-images.githubusercontent.com/1769696/155147515-3b9e12fc-a079-4bfc-bb0a-89d5ef4f05cf.png)

**Comment by beprogressive** [comment]
if I embed flurryCrash as
```
flurryCrash {
    apiKey "<My API key>"
    token "<My very long token>"
}
```
get exception `You must provide a valid token`.
If I add `useEnvVar false` - get `The value for property 'resValues' cannot be changed any further` again.

**Comment by dscherba** [comment]
@beprogressive : we're working on addressing this/releasing an updated version of the Flurry symbol-upload plugin: https://github.com/flurry/upload-clients/pull/46

Prior to release, you can pull and build/publish this branch into your local maven cache (`gradle assemble publishToMavenLocal`) and then update your `build.gradle` to reference the new/local version:

```
buildscript {
   ...
   dependencies {
      ...
      classpath "com.flurry:symbol-upload:4.2.0"
   }
   ...
}
```

**Comment by dscherba** [comment]
Update: com.flurry:symbol-upload:4.2.0 has been published: https://plugins.gradle.org/plugin/com.flurry.android.symbols
