### ISSUE TITLE
 error looking up project. (GET https://crash-metadata.flurry.com/pulse/v1/project?filter[project.apiKey]=xxx&fields[project]=apiKey => 401) UNAUTHORIZED (Bad Token)  

### ISSUE THREAD

**Issue by ytandhz** [flurry/upload-clients#51]

**Comment by amtos** [comment]
Please make sure you are using and overriding the correct API access token from README. More information here: https://developer.yahoo.com/flurry/docs/api/code/apptoken/ . If you still face this issue, please send the full exception stacktrace with details like time of error, project id, app name, company name to support@flurry.com

**Comment by ytandhz** [comment]
您的邮件我已收到，谢谢您的来信！

**Comment by ytandhz** [comment]
> 

thank you for the response, I added Programmatic User and reconfigured token in flurry.config. Now , we've solved that problem
